Make sure network autoconfiguration is clean [tracker #2991]

diff --git a/packaging/network-configuration-event b/packaging/network-configuration-event
--- a/packaging/network-configuration-event
+++ b/packaging/network-configuration-event
@@ -9,7 +9,16 @@ AUTO_CONFIG=`grep "^auto_configure[[:space:]]*=[[:space:]]*yes" /etc/clearos/pri
 if [ -d /etc/cups ]; then
     echo "# Automatically generated by init script" > /etc/cups/cupsd.listen.conf.auto
     LANIPS=`/usr/sbin/network --get-lan-ips 2>/dev/null`
+    RETVAL=$?
 
+    # Bail if bad exit code
+    if [ $RETVAL -ne 0 ]; then
+        echo "# Unable to find LAN IPs (error $RETVAL)" >> /etc/cups/cupsd.listen.conf.auto
+        exit 1
+    fi
+
+    # Not all PHP warnings are suppressed, so only grab last line for now
+    LANIPS=`/usr/sbin/network --get-lan-ips 2>/dev/null | /usr/bin/tail -n1`
     for IP in $LANIPS 127.0.0.1; do
         echo "Listen $IP:631" >> /etc/cups/cupsd.listen.conf.auto
     done
